// **********************************************************************
//
// Copyright (c) 2003-2010 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************

// Ice version 3.4.0

package cn.joy.ggg.api.model;

// <auto-generated>
//
// Generated from file `community.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>


public final class CollectlistHolder
{
    public
    CollectlistHolder()
    {
    }

    public
    CollectlistHolder(java.util.List<Collect> value)
    {
        this.value = value;
    }

    public java.util.List<Collect> value;
}
