// **********************************************************************
//
// Copyright (c) 2003-2010 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************

// Ice version 3.4.0

package cn.joy.ggg.api.model;

// <auto-generated>
//
// Generated from file `community.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>


public class PageSupport implements java.lang.Cloneable, java.io.Serializable
{
    public int pageNo;

    public int pageSize;

    public int totalSize;

    public Ice.Object result;

    public PageSupport()
    {
    }

    public PageSupport(int pageNo, int pageSize, int totalSize, Ice.Object result)
    {
        this.pageNo = pageNo;
        this.pageSize = pageSize;
        this.totalSize = totalSize;
        this.result = result;
    }

    public boolean
    equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        PageSupport _r = null;
        try
        {
            _r = (PageSupport)rhs;
        }
        catch(ClassCastException ex)
        {
        }

        if(_r != null)
        {
            if(pageNo != _r.pageNo)
            {
                return false;
            }
            if(pageSize != _r.pageSize)
            {
                return false;
            }
            if(totalSize != _r.totalSize)
            {
                return false;
            }
            if(result != _r.result && result != null && !result.equals(_r.result))
            {
                return false;
            }

            return true;
        }

        return false;
    }

    public int
    hashCode()
    {
        int __h = 0;
        __h = 5 * __h + pageNo;
        __h = 5 * __h + pageSize;
        __h = 5 * __h + totalSize;
        if(result != null)
        {
            __h = 5 * __h + result.hashCode();
        }
        return __h;
    }

    public java.lang.Object
    clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void
    __write(IceInternal.BasicStream __os)
    {
        __os.writeInt(pageNo);
        __os.writeInt(pageSize);
        __os.writeInt(totalSize);
        __os.writeObject(result);
    }

    private class Patcher implements IceInternal.Patcher
    {
        public void
        patch(Ice.Object v)
        {
            try
            {
                result = (Ice.Object)v;
            }
            catch(ClassCastException ex)
            {
                IceInternal.Ex.throwUOE(type(), v.ice_id());
            }
        }

        public String
        type()
        {
            return "::Ice::Object";
        }
    }

    public void
    __read(IceInternal.BasicStream __is)
    {
        pageNo = __is.readInt();
        pageSize = __is.readInt();
        totalSize = __is.readInt();
        __is.readObject(new Patcher());
    }

    public int getPageNo() {
      return pageNo;
    }

    public void setPageNo(int pageNo) {
      this.pageNo = pageNo;
    }

    public int getPageSize() {
      return pageSize;
    }

    public void setPageSize(int pageSize) {
      this.pageSize = pageSize;
    }

    public int getTotalSize() {
      return totalSize;
    }

    public void setTotalSize(int totalSize) {
      this.totalSize = totalSize;
    }

    public Ice.Object getResult() {
      return result;
    }

    public void setResult(Ice.Object result) {
      this.result = result;
    }
}
