// **********************************************************************
//
// Copyright (c) 2003-2010 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************

// Ice version 3.4.0

package cn.joy.ggg.api.model;

// <auto-generated>
//
// Generated from file `uac.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>


public class UACResponse implements java.lang.Cloneable, java.io.Serializable
{
    public String code;

    public UAC info;

    public UACResponse()
    {
    }

    public UACResponse(String code, UAC info)
    {
        this.code = code;
        this.info = info;
    }

    public boolean
    equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        UACResponse _r = null;
        try
        {
            _r = (UACResponse)rhs;
        }
        catch(ClassCastException ex)
        {
        }

        if(_r != null)
        {
            if(code != _r.code && code != null && !code.equals(_r.code))
            {
                return false;
            }
            if(info != _r.info && info != null && !info.equals(_r.info))
            {
                return false;
            }

            return true;
        }

        return false;
    }

    public int
    hashCode()
    {
        int __h = 0;
        if(code != null)
        {
            __h = 5 * __h + code.hashCode();
        }
        if(info != null)
        {
            __h = 5 * __h + info.hashCode();
        }
        return __h;
    }

    public java.lang.Object
    clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void
    __write(IceInternal.BasicStream __os)
    {
        __os.writeString(code);
        info.__write(__os);
    }

    public void
    __read(IceInternal.BasicStream __is)
    {
        code = __is.readString();
        info = new UAC();
        info.__read(__is);
    }

    public String getCode() {
      return code;
    }

    public void setCode(String code) {
      this.code = code;
    }

    public UAC getInfo() {
      return info;
    }

    public void setInfo(UAC info) {
      this.info = info;
    }
}
