// **********************************************************************
//
// Copyright (c) 2003-2010 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************

// Ice version 3.4.0

package cn.joy.ggg.api.model;

// <auto-generated>
//
// Generated from file `community.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>


public class UserProfile implements java.lang.Cloneable, java.io.Serializable
{
    public String userid;

    public String password;

    public String name;

    public String nick;

    public String area;

    public String sex;

    public String age;

    public String birthday;

    public String constellation;

    public String ability;

    public String sign;

    public UserProfile()
    {
    }

    public UserProfile(String userid, String password, String name, String nick, String area, String sex, String age, String birthday, String constellation, String ability, String sign)
    {
        this.userid = userid;
        this.password = password;
        this.name = name;
        this.nick = nick;
        this.area = area;
        this.sex = sex;
        this.age = age;
        this.birthday = birthday;
        this.constellation = constellation;
        this.ability = ability;
        this.sign = sign;
    }

    public boolean
    equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        UserProfile _r = null;
        try
        {
            _r = (UserProfile)rhs;
        }
        catch(ClassCastException ex)
        {
        }

        if(_r != null)
        {
            if(userid != _r.userid && userid != null && !userid.equals(_r.userid))
            {
                return false;
            }
            if(password != _r.password && password != null && !password.equals(_r.password))
            {
                return false;
            }
            if(name != _r.name && name != null && !name.equals(_r.name))
            {
                return false;
            }
            if(nick != _r.nick && nick != null && !nick.equals(_r.nick))
            {
                return false;
            }
            if(area != _r.area && area != null && !area.equals(_r.area))
            {
                return false;
            }
            if(sex != _r.sex && sex != null && !sex.equals(_r.sex))
            {
                return false;
            }
            if(age != _r.age && age != null && !age.equals(_r.age))
            {
                return false;
            }
            if(birthday != _r.birthday && birthday != null && !birthday.equals(_r.birthday))
            {
                return false;
            }
            if(constellation != _r.constellation && constellation != null && !constellation.equals(_r.constellation))
            {
                return false;
            }
            if(ability != _r.ability && ability != null && !ability.equals(_r.ability))
            {
                return false;
            }
            if(sign != _r.sign && sign != null && !sign.equals(_r.sign))
            {
                return false;
            }

            return true;
        }

        return false;
    }

    public int
    hashCode()
    {
        int __h = 0;
        if(userid != null)
        {
            __h = 5 * __h + userid.hashCode();
        }
        if(password != null)
        {
            __h = 5 * __h + password.hashCode();
        }
        if(name != null)
        {
            __h = 5 * __h + name.hashCode();
        }
        if(nick != null)
        {
            __h = 5 * __h + nick.hashCode();
        }
        if(area != null)
        {
            __h = 5 * __h + area.hashCode();
        }
        if(sex != null)
        {
            __h = 5 * __h + sex.hashCode();
        }
        if(age != null)
        {
            __h = 5 * __h + age.hashCode();
        }
        if(birthday != null)
        {
            __h = 5 * __h + birthday.hashCode();
        }
        if(constellation != null)
        {
            __h = 5 * __h + constellation.hashCode();
        }
        if(ability != null)
        {
            __h = 5 * __h + ability.hashCode();
        }
        if(sign != null)
        {
            __h = 5 * __h + sign.hashCode();
        }
        return __h;
    }

    public java.lang.Object
    clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void
    __write(IceInternal.BasicStream __os)
    {
        __os.writeString(userid);
        __os.writeString(password);
        __os.writeString(name);
        __os.writeString(nick);
        __os.writeString(area);
        __os.writeString(sex);
        __os.writeString(age);
        __os.writeString(birthday);
        __os.writeString(constellation);
        __os.writeString(ability);
        __os.writeString(sign);
    }

    public void
    __read(IceInternal.BasicStream __is)
    {
        userid = __is.readString();
        password = __is.readString();
        name = __is.readString();
        nick = __is.readString();
        area = __is.readString();
        sex = __is.readString();
        age = __is.readString();
        birthday = __is.readString();
        constellation = __is.readString();
        ability = __is.readString();
        sign = __is.readString();
    }

    public String getUserid() {
      return userid;
    }

    public void setUserid(String userid) {
      this.userid = userid;
    }

    public String getPassword() {
      return password;
    }

    public void setPassword(String password) {
      this.password = password;
    }

    public String getName() {
      return name;
    }

    public void setName(String name) {
      this.name = name;
    }

    public String getNick() {
      return nick;
    }

    public void setNick(String nick) {
      this.nick = nick;
    }

    public String getArea() {
      return area;
    }

    public void setArea(String area) {
      this.area = area;
    }

    public String getSex() {
      return sex;
    }

    public void setSex(String sex) {
      this.sex = sex;
    }

    public String getAge() {
      return age;
    }

    public void setAge(String age) {
      this.age = age;
    }

    public String getBirthday() {
      return birthday;
    }

    public void setBirthday(String birthday) {
      this.birthday = birthday;
    }

    public String getConstellation() {
      return constellation;
    }

    public void setConstellation(String constellation) {
      this.constellation = constellation;
    }

    public String getAbility() {
      return ability;
    }

    public void setAbility(String ability) {
      this.ability = ability;
    }

    public String getSign() {
      return sign;
    }

    public void setSign(String sign) {
      this.sign = sign;
    }
}
