// **********************************************************************
//
// Copyright (c) 2003-2010 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************

// Ice version 3.4.0

package cn.joy.ggg.api.service;

// <auto-generated>
//
// Generated from file `community.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>


public interface _CommunityServiceOperations
{
    java.util.List<cn.joy.ggg.api.model.UserProfile> searchUser(cn.joy.ggg.api.model.UserProfile user, Ice.Current __current);

    int setUser(cn.joy.ggg.api.model.UserProfile user, Ice.Current __current);

    cn.joy.ggg.api.model.UserProfile getUser(String userid, Ice.Current __current);

    int addCollect(String userid, String title, String link, Ice.Current __current);

    int removeCollect(String userid, String collectid, Ice.Current __current);

    cn.joy.ggg.api.model.PageSupport getList(String userid, int pageNo, int pageSize, Ice.Current __current);

    cn.joy.ggg.api.model.PageSupport getScoringHistory(String userid, int pageNo, int pageSize, Ice.Current __current);

    cn.joy.ggg.api.model.PageSupport getTopicList(String userid, int pageNo, int pageSize, Ice.Current __current);

    int addTopic(String userid, cn.joy.ggg.api.model.Topic tipoc, Ice.Current __current);

    int removeTopic(String userid, String tid, Ice.Current __current);

    int setTopic(String userid, cn.joy.ggg.api.model.Topic topic, Ice.Current __current);

    void encodeNotify(cn.joy.ggg.api.model.Topic topic, Ice.Current __current);

    cn.joy.ggg.api.model.PageSupport getFriendDevelopment(String userId, int pageNo, int pageSize, Ice.Current __current);

    cn.joy.ggg.api.model.PageSupport getSelfDevelopment(String selfId, int pageNo, int pageSize, Ice.Current __current);

    int addDevelopment(cn.joy.ggg.api.model.FriendDevelopment devel, Ice.Current __current);
}
