// **********************************************************************
//
// Copyright (c) 2003-2010 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************

// Ice version 3.4.0

package cn.joy.ggg.api.service;

// <auto-generated>
//
// Generated from file `message.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>


public interface _MessageServiceOperationsNC
{
    cn.joy.ggg.api.model.MessageResponse sendMessage(String source, String dest, String msg);

    cn.joy.ggg.api.model.MessageResponse getMessageList(String source, int start, int count);

    cn.joy.ggg.api.model.MessageResponse removeMessage(String source, int msgId);
}
