// **********************************************************************
//
// Copyright (c) 2003-2010 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************

// Ice version 3.4.0

package cn.joy.ggg.api.service;

// <auto-generated>
//
// Generated from file `comment.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>


public interface CommentServicePrx extends Ice.ObjectPrx
{
    public cn.joy.ggg.api.model.CommentResponse postComment(String appId, String userId, String cid, String connect, boolean isAnonymity);

    public cn.joy.ggg.api.model.CommentResponse postComment(String appId, String userId, String cid, String connect, boolean isAnonymity, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_postComment(String appId, String userId, String cid, String connect, boolean isAnonymity);

    public Ice.AsyncResult begin_postComment(String appId, String userId, String cid, String connect, boolean isAnonymity, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_postComment(String appId, String userId, String cid, String connect, boolean isAnonymity, Ice.Callback __cb);

    public Ice.AsyncResult begin_postComment(String appId, String userId, String cid, String connect, boolean isAnonymity, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_postComment(String appId, String userId, String cid, String connect, boolean isAnonymity, Callback_CommentService_postComment __cb);

    public Ice.AsyncResult begin_postComment(String appId, String userId, String cid, String connect, boolean isAnonymity, java.util.Map<String, String> __ctx, Callback_CommentService_postComment __cb);

    public cn.joy.ggg.api.model.CommentResponse end_postComment(Ice.AsyncResult __result);

    public cn.joy.ggg.api.model.CommentResponse getCommentList(String appId, String cid, int start, int limit);

    public cn.joy.ggg.api.model.CommentResponse getCommentList(String appId, String cid, int start, int limit, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getCommentList(String appId, String cid, int start, int limit);

    public Ice.AsyncResult begin_getCommentList(String appId, String cid, int start, int limit, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getCommentList(String appId, String cid, int start, int limit, Ice.Callback __cb);

    public Ice.AsyncResult begin_getCommentList(String appId, String cid, int start, int limit, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_getCommentList(String appId, String cid, int start, int limit, Callback_CommentService_getCommentList __cb);

    public Ice.AsyncResult begin_getCommentList(String appId, String cid, int start, int limit, java.util.Map<String, String> __ctx, Callback_CommentService_getCommentList __cb);

    public cn.joy.ggg.api.model.CommentResponse end_getCommentList(Ice.AsyncResult __result);

    public cn.joy.ggg.api.model.CommentResponse removeComment(String appId, String cid, String commentIds);

    public cn.joy.ggg.api.model.CommentResponse removeComment(String appId, String cid, String commentIds, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_removeComment(String appId, String cid, String commentIds);

    public Ice.AsyncResult begin_removeComment(String appId, String cid, String commentIds, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_removeComment(String appId, String cid, String commentIds, Ice.Callback __cb);

    public Ice.AsyncResult begin_removeComment(String appId, String cid, String commentIds, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_removeComment(String appId, String cid, String commentIds, Callback_CommentService_removeComment __cb);

    public Ice.AsyncResult begin_removeComment(String appId, String cid, String commentIds, java.util.Map<String, String> __ctx, Callback_CommentService_removeComment __cb);

    public cn.joy.ggg.api.model.CommentResponse end_removeComment(Ice.AsyncResult __result);
}
