// **********************************************************************
//
// Copyright (c) 2003-2010 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************

// Ice version 3.4.0

package cn.joy.ggg.api.service;

// <auto-generated>
//
// Generated from file `comment.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>


public final class CommentServicePrxHolder
{
    public
    CommentServicePrxHolder()
    {
    }

    public
    CommentServicePrxHolder(CommentServicePrx value)
    {
        this.value = value;
    }

    public CommentServicePrx value;
}
