// **********************************************************************
//
// Copyright (c) 2003-2010 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************

// Ice version 3.4.0

package cn.joy.ggg.api.service;

// <auto-generated>
//
// Generated from file `relation.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>


public interface RelationServicePrx extends Ice.ObjectPrx
{
    public cn.joy.ggg.api.model.RelationResponse addFriend(String self, String buddy, String description);

    public cn.joy.ggg.api.model.RelationResponse addFriend(String self, String buddy, String description, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_addFriend(String self, String buddy, String description);

    public Ice.AsyncResult begin_addFriend(String self, String buddy, String description, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_addFriend(String self, String buddy, String description, Ice.Callback __cb);

    public Ice.AsyncResult begin_addFriend(String self, String buddy, String description, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_addFriend(String self, String buddy, String description, Callback_RelationService_addFriend __cb);

    public Ice.AsyncResult begin_addFriend(String self, String buddy, String description, java.util.Map<String, String> __ctx, Callback_RelationService_addFriend __cb);

    public cn.joy.ggg.api.model.RelationResponse end_addFriend(Ice.AsyncResult __result);

    public cn.joy.ggg.api.model.RelationResponse removeFriend(String self, String buddy);

    public cn.joy.ggg.api.model.RelationResponse removeFriend(String self, String buddy, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_removeFriend(String self, String buddy);

    public Ice.AsyncResult begin_removeFriend(String self, String buddy, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_removeFriend(String self, String buddy, Ice.Callback __cb);

    public Ice.AsyncResult begin_removeFriend(String self, String buddy, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_removeFriend(String self, String buddy, Callback_RelationService_removeFriend __cb);

    public Ice.AsyncResult begin_removeFriend(String self, String buddy, java.util.Map<String, String> __ctx, Callback_RelationService_removeFriend __cb);

    public cn.joy.ggg.api.model.RelationResponse end_removeFriend(Ice.AsyncResult __result);

    public cn.joy.ggg.api.model.RelationResponse getFriendList(String self, int start, int count);

    public cn.joy.ggg.api.model.RelationResponse getFriendList(String self, int start, int count, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getFriendList(String self, int start, int count);

    public Ice.AsyncResult begin_getFriendList(String self, int start, int count, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getFriendList(String self, int start, int count, Ice.Callback __cb);

    public Ice.AsyncResult begin_getFriendList(String self, int start, int count, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_getFriendList(String self, int start, int count, Callback_RelationService_getFriendList __cb);

    public Ice.AsyncResult begin_getFriendList(String self, int start, int count, java.util.Map<String, String> __ctx, Callback_RelationService_getFriendList __cb);

    public cn.joy.ggg.api.model.RelationResponse end_getFriendList(Ice.AsyncResult __result);
}
