// **********************************************************************
//
// Copyright (c) 2003-2010 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************

// Ice version 3.4.0

package cn.joy.ggg.api.service;

// <auto-generated>
//
// Generated from file `relation.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>


public final class RelationServicePrxHelper extends Ice.ObjectPrxHelperBase implements RelationServicePrx
{
    public cn.joy.ggg.api.model.RelationResponse
    addFriend(String self, String buddy, String description)
    {
        return addFriend(self, buddy, description, null, false);
    }

    public cn.joy.ggg.api.model.RelationResponse
    addFriend(String self, String buddy, String description, java.util.Map<String, String> __ctx)
    {
        return addFriend(self, buddy, description, __ctx, true);
    }

    private cn.joy.ggg.api.model.RelationResponse
    addFriend(String self, String buddy, String description, java.util.Map<String, String> __ctx, boolean __explicitCtx)
    {
        if(__explicitCtx && __ctx == null)
        {
            __ctx = _emptyContext;
        }
        int __cnt = 0;
        while(true)
        {
            Ice._ObjectDel __delBase = null;
            try
            {
                __checkTwowayOnly("addFriend");
                __delBase = __getDelegate(false);
                _RelationServiceDel __del = (_RelationServiceDel)__delBase;
                return __del.addFriend(self, buddy, description, __ctx);
            }
            catch(IceInternal.LocalExceptionWrapper __ex)
            {
                __handleExceptionWrapper(__delBase, __ex);
            }
            catch(Ice.LocalException __ex)
            {
                __cnt = __handleException(__delBase, __ex, null, __cnt);
            }
        }
    }

    private static final String __addFriend_name = "addFriend";

    public Ice.AsyncResult begin_addFriend(String self, String buddy, String description)
    {
        return begin_addFriend(self, buddy, description, null, false, null);
    }

    public Ice.AsyncResult begin_addFriend(String self, String buddy, String description, java.util.Map<String, String> __ctx)
    {
        return begin_addFriend(self, buddy, description, __ctx, true, null);
    }

    public Ice.AsyncResult begin_addFriend(String self, String buddy, String description, Ice.Callback __cb)
    {
        return begin_addFriend(self, buddy, description, null, false, __cb);
    }

    public Ice.AsyncResult begin_addFriend(String self, String buddy, String description, java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_addFriend(self, buddy, description, __ctx, true, __cb);
    }

    public Ice.AsyncResult begin_addFriend(String self, String buddy, String description, Callback_RelationService_addFriend __cb)
    {
        return begin_addFriend(self, buddy, description, null, false, __cb);
    }

    public Ice.AsyncResult begin_addFriend(String self, String buddy, String description, java.util.Map<String, String> __ctx, Callback_RelationService_addFriend __cb)
    {
        return begin_addFriend(self, buddy, description, __ctx, true, __cb);
    }

    private Ice.AsyncResult begin_addFriend(String self, String buddy, String description, java.util.Map<String, String> __ctx, boolean __explicitCtx, IceInternal.CallbackBase __cb)
    {
        __checkAsyncTwowayOnly(__addFriend_name);
        IceInternal.OutgoingAsync __result = new IceInternal.OutgoingAsync(this, __addFriend_name, __cb);
        try
        {
            __result.__prepare(__addFriend_name, Ice.OperationMode.Normal, __ctx, __explicitCtx);
            IceInternal.BasicStream __os = __result.__os();
            __os.writeString(self);
            __os.writeString(buddy);
            __os.writeString(description);
            __os.endWriteEncaps();
            __result.__send(true);
        }
        catch(Ice.LocalException __ex)
        {
            __result.__exceptionAsync(__ex);
        }
        return __result;
    }

    public cn.joy.ggg.api.model.RelationResponse end_addFriend(Ice.AsyncResult __result)
    {
        Ice.AsyncResult.__check(__result, this, __addFriend_name);
        if(!__result.__wait())
        {
            try
            {
                __result.__throwUserException();
            }
            catch(Ice.UserException __ex)
            {
                throw new Ice.UnknownUserException(__ex.ice_name());
            }
        }
        cn.joy.ggg.api.model.RelationResponse __ret;
        IceInternal.BasicStream __is = __result.__is();
        __is.startReadEncaps();
        __ret = new cn.joy.ggg.api.model.RelationResponse();
        __ret.__read(__is);
        __is.endReadEncaps();
        return __ret;
    }

    public cn.joy.ggg.api.model.RelationResponse
    getFriendList(String self, int start, int count)
    {
        return getFriendList(self, start, count, null, false);
    }

    public cn.joy.ggg.api.model.RelationResponse
    getFriendList(String self, int start, int count, java.util.Map<String, String> __ctx)
    {
        return getFriendList(self, start, count, __ctx, true);
    }

    private cn.joy.ggg.api.model.RelationResponse
    getFriendList(String self, int start, int count, java.util.Map<String, String> __ctx, boolean __explicitCtx)
    {
        if(__explicitCtx && __ctx == null)
        {
            __ctx = _emptyContext;
        }
        int __cnt = 0;
        while(true)
        {
            Ice._ObjectDel __delBase = null;
            try
            {
                __checkTwowayOnly("getFriendList");
                __delBase = __getDelegate(false);
                _RelationServiceDel __del = (_RelationServiceDel)__delBase;
                return __del.getFriendList(self, start, count, __ctx);
            }
            catch(IceInternal.LocalExceptionWrapper __ex)
            {
                __handleExceptionWrapper(__delBase, __ex);
            }
            catch(Ice.LocalException __ex)
            {
                __cnt = __handleException(__delBase, __ex, null, __cnt);
            }
        }
    }

    private static final String __getFriendList_name = "getFriendList";

    public Ice.AsyncResult begin_getFriendList(String self, int start, int count)
    {
        return begin_getFriendList(self, start, count, null, false, null);
    }

    public Ice.AsyncResult begin_getFriendList(String self, int start, int count, java.util.Map<String, String> __ctx)
    {
        return begin_getFriendList(self, start, count, __ctx, true, null);
    }

    public Ice.AsyncResult begin_getFriendList(String self, int start, int count, Ice.Callback __cb)
    {
        return begin_getFriendList(self, start, count, null, false, __cb);
    }

    public Ice.AsyncResult begin_getFriendList(String self, int start, int count, java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_getFriendList(self, start, count, __ctx, true, __cb);
    }

    public Ice.AsyncResult begin_getFriendList(String self, int start, int count, Callback_RelationService_getFriendList __cb)
    {
        return begin_getFriendList(self, start, count, null, false, __cb);
    }

    public Ice.AsyncResult begin_getFriendList(String self, int start, int count, java.util.Map<String, String> __ctx, Callback_RelationService_getFriendList __cb)
    {
        return begin_getFriendList(self, start, count, __ctx, true, __cb);
    }

    private Ice.AsyncResult begin_getFriendList(String self, int start, int count, java.util.Map<String, String> __ctx, boolean __explicitCtx, IceInternal.CallbackBase __cb)
    {
        __checkAsyncTwowayOnly(__getFriendList_name);
        IceInternal.OutgoingAsync __result = new IceInternal.OutgoingAsync(this, __getFriendList_name, __cb);
        try
        {
            __result.__prepare(__getFriendList_name, Ice.OperationMode.Normal, __ctx, __explicitCtx);
            IceInternal.BasicStream __os = __result.__os();
            __os.writeString(self);
            __os.writeInt(start);
            __os.writeInt(count);
            __os.endWriteEncaps();
            __result.__send(true);
        }
        catch(Ice.LocalException __ex)
        {
            __result.__exceptionAsync(__ex);
        }
        return __result;
    }

    public cn.joy.ggg.api.model.RelationResponse end_getFriendList(Ice.AsyncResult __result)
    {
        Ice.AsyncResult.__check(__result, this, __getFriendList_name);
        if(!__result.__wait())
        {
            try
            {
                __result.__throwUserException();
            }
            catch(Ice.UserException __ex)
            {
                throw new Ice.UnknownUserException(__ex.ice_name());
            }
        }
        cn.joy.ggg.api.model.RelationResponse __ret;
        IceInternal.BasicStream __is = __result.__is();
        __is.startReadEncaps();
        __ret = new cn.joy.ggg.api.model.RelationResponse();
        __ret.__read(__is);
        __is.endReadEncaps();
        return __ret;
    }

    public cn.joy.ggg.api.model.RelationResponse
    removeFriend(String self, String buddy)
    {
        return removeFriend(self, buddy, null, false);
    }

    public cn.joy.ggg.api.model.RelationResponse
    removeFriend(String self, String buddy, java.util.Map<String, String> __ctx)
    {
        return removeFriend(self, buddy, __ctx, true);
    }

    private cn.joy.ggg.api.model.RelationResponse
    removeFriend(String self, String buddy, java.util.Map<String, String> __ctx, boolean __explicitCtx)
    {
        if(__explicitCtx && __ctx == null)
        {
            __ctx = _emptyContext;
        }
        int __cnt = 0;
        while(true)
        {
            Ice._ObjectDel __delBase = null;
            try
            {
                __checkTwowayOnly("removeFriend");
                __delBase = __getDelegate(false);
                _RelationServiceDel __del = (_RelationServiceDel)__delBase;
                return __del.removeFriend(self, buddy, __ctx);
            }
            catch(IceInternal.LocalExceptionWrapper __ex)
            {
                __handleExceptionWrapper(__delBase, __ex);
            }
            catch(Ice.LocalException __ex)
            {
                __cnt = __handleException(__delBase, __ex, null, __cnt);
            }
        }
    }

    private static final String __removeFriend_name = "removeFriend";

    public Ice.AsyncResult begin_removeFriend(String self, String buddy)
    {
        return begin_removeFriend(self, buddy, null, false, null);
    }

    public Ice.AsyncResult begin_removeFriend(String self, String buddy, java.util.Map<String, String> __ctx)
    {
        return begin_removeFriend(self, buddy, __ctx, true, null);
    }

    public Ice.AsyncResult begin_removeFriend(String self, String buddy, Ice.Callback __cb)
    {
        return begin_removeFriend(self, buddy, null, false, __cb);
    }

    public Ice.AsyncResult begin_removeFriend(String self, String buddy, java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_removeFriend(self, buddy, __ctx, true, __cb);
    }

    public Ice.AsyncResult begin_removeFriend(String self, String buddy, Callback_RelationService_removeFriend __cb)
    {
        return begin_removeFriend(self, buddy, null, false, __cb);
    }

    public Ice.AsyncResult begin_removeFriend(String self, String buddy, java.util.Map<String, String> __ctx, Callback_RelationService_removeFriend __cb)
    {
        return begin_removeFriend(self, buddy, __ctx, true, __cb);
    }

    private Ice.AsyncResult begin_removeFriend(String self, String buddy, java.util.Map<String, String> __ctx, boolean __explicitCtx, IceInternal.CallbackBase __cb)
    {
        __checkAsyncTwowayOnly(__removeFriend_name);
        IceInternal.OutgoingAsync __result = new IceInternal.OutgoingAsync(this, __removeFriend_name, __cb);
        try
        {
            __result.__prepare(__removeFriend_name, Ice.OperationMode.Normal, __ctx, __explicitCtx);
            IceInternal.BasicStream __os = __result.__os();
            __os.writeString(self);
            __os.writeString(buddy);
            __os.endWriteEncaps();
            __result.__send(true);
        }
        catch(Ice.LocalException __ex)
        {
            __result.__exceptionAsync(__ex);
        }
        return __result;
    }

    public cn.joy.ggg.api.model.RelationResponse end_removeFriend(Ice.AsyncResult __result)
    {
        Ice.AsyncResult.__check(__result, this, __removeFriend_name);
        if(!__result.__wait())
        {
            try
            {
                __result.__throwUserException();
            }
            catch(Ice.UserException __ex)
            {
                throw new Ice.UnknownUserException(__ex.ice_name());
            }
        }
        cn.joy.ggg.api.model.RelationResponse __ret;
        IceInternal.BasicStream __is = __result.__is();
        __is.startReadEncaps();
        __ret = new cn.joy.ggg.api.model.RelationResponse();
        __ret.__read(__is);
        __is.endReadEncaps();
        return __ret;
    }

    public static RelationServicePrx
    checkedCast(Ice.ObjectPrx __obj)
    {
        RelationServicePrx __d = null;
        if(__obj != null)
        {
            try
            {
                __d = (RelationServicePrx)__obj;
            }
            catch(ClassCastException ex)
            {
                if(__obj.ice_isA("::service::RelationService"))
                {
                    RelationServicePrxHelper __h = new RelationServicePrxHelper();
                    __h.__copyFrom(__obj);
                    __d = __h;
                }
            }
        }
        return __d;
    }

    public static RelationServicePrx
    checkedCast(Ice.ObjectPrx __obj, java.util.Map<String, String> __ctx)
    {
        RelationServicePrx __d = null;
        if(__obj != null)
        {
            try
            {
                __d = (RelationServicePrx)__obj;
            }
            catch(ClassCastException ex)
            {
                if(__obj.ice_isA("::service::RelationService", __ctx))
                {
                    RelationServicePrxHelper __h = new RelationServicePrxHelper();
                    __h.__copyFrom(__obj);
                    __d = __h;
                }
            }
        }
        return __d;
    }

    public static RelationServicePrx
    checkedCast(Ice.ObjectPrx __obj, String __facet)
    {
        RelationServicePrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            try
            {
                if(__bb.ice_isA("::service::RelationService"))
                {
                    RelationServicePrxHelper __h = new RelationServicePrxHelper();
                    __h.__copyFrom(__bb);
                    __d = __h;
                }
            }
            catch(Ice.FacetNotExistException ex)
            {
            }
        }
        return __d;
    }

    public static RelationServicePrx
    checkedCast(Ice.ObjectPrx __obj, String __facet, java.util.Map<String, String> __ctx)
    {
        RelationServicePrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            try
            {
                if(__bb.ice_isA("::service::RelationService", __ctx))
                {
                    RelationServicePrxHelper __h = new RelationServicePrxHelper();
                    __h.__copyFrom(__bb);
                    __d = __h;
                }
            }
            catch(Ice.FacetNotExistException ex)
            {
            }
        }
        return __d;
    }

    public static RelationServicePrx
    uncheckedCast(Ice.ObjectPrx __obj)
    {
        RelationServicePrx __d = null;
        if(__obj != null)
        {
            try
            {
                __d = (RelationServicePrx)__obj;
            }
            catch(ClassCastException ex)
            {
                RelationServicePrxHelper __h = new RelationServicePrxHelper();
                __h.__copyFrom(__obj);
                __d = __h;
            }
        }
        return __d;
    }

    public static RelationServicePrx
    uncheckedCast(Ice.ObjectPrx __obj, String __facet)
    {
        RelationServicePrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            RelationServicePrxHelper __h = new RelationServicePrxHelper();
            __h.__copyFrom(__bb);
            __d = __h;
        }
        return __d;
    }

    protected Ice._ObjectDelM
    __createDelegateM()
    {
        return new _RelationServiceDelM();
    }

    protected Ice._ObjectDelD
    __createDelegateD()
    {
        return new _RelationServiceDelD();
    }

    public static void
    __write(IceInternal.BasicStream __os, RelationServicePrx v)
    {
        __os.writeProxy(v);
    }

    public static RelationServicePrx
    __read(IceInternal.BasicStream __is)
    {
        Ice.ObjectPrx proxy = __is.readProxy();
        if(proxy != null)
        {
            RelationServicePrxHelper result = new RelationServicePrxHelper();
            result.__copyFrom(proxy);
            return result;
        }
        return null;
    }
}
