// **********************************************************************
//
// Copyright (c) 2003-2010 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************

// Ice version 3.4.0

package cn.joy.ggg.api.model;

// <auto-generated>
//
// Generated from file `comment.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>


public class Comment implements java.lang.Cloneable, java.io.Serializable
{
    public String comId;

    public String appId;

    public String contentId;

    public String content;

    public String userId;

    public String userName;

    public String nick;

    public String ip;

    public String provinceId;

    public String provinceName;

    public String isUserUBB;

    public String createTime;

    public Comment()
    {
    }

    public Comment(String comId, String appId, String contentId, String content, String userId, String userName, String nick, String ip, String provinceId, String provinceName, String isUserUBB, String createTime)
    {
        this.comId = comId;
        this.appId = appId;
        this.contentId = contentId;
        this.content = content;
        this.userId = userId;
        this.userName = userName;
        this.nick = nick;
        this.ip = ip;
        this.provinceId = provinceId;
        this.provinceName = provinceName;
        this.isUserUBB = isUserUBB;
        this.createTime = createTime;
    }

    public boolean
    equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        Comment _r = null;
        try
        {
            _r = (Comment)rhs;
        }
        catch(ClassCastException ex)
        {
        }

        if(_r != null)
        {
            if(comId != _r.comId && comId != null && !comId.equals(_r.comId))
            {
                return false;
            }
            if(appId != _r.appId && appId != null && !appId.equals(_r.appId))
            {
                return false;
            }
            if(contentId != _r.contentId && contentId != null && !contentId.equals(_r.contentId))
            {
                return false;
            }
            if(content != _r.content && content != null && !content.equals(_r.content))
            {
                return false;
            }
            if(userId != _r.userId && userId != null && !userId.equals(_r.userId))
            {
                return false;
            }
            if(userName != _r.userName && userName != null && !userName.equals(_r.userName))
            {
                return false;
            }
            if(nick != _r.nick && nick != null && !nick.equals(_r.nick))
            {
                return false;
            }
            if(ip != _r.ip && ip != null && !ip.equals(_r.ip))
            {
                return false;
            }
            if(provinceId != _r.provinceId && provinceId != null && !provinceId.equals(_r.provinceId))
            {
                return false;
            }
            if(provinceName != _r.provinceName && provinceName != null && !provinceName.equals(_r.provinceName))
            {
                return false;
            }
            if(isUserUBB != _r.isUserUBB && isUserUBB != null && !isUserUBB.equals(_r.isUserUBB))
            {
                return false;
            }
            if(createTime != _r.createTime && createTime != null && !createTime.equals(_r.createTime))
            {
                return false;
            }

            return true;
        }

        return false;
    }

    public int
    hashCode()
    {
        int __h = 0;
        if(comId != null)
        {
            __h = 5 * __h + comId.hashCode();
        }
        if(appId != null)
        {
            __h = 5 * __h + appId.hashCode();
        }
        if(contentId != null)
        {
            __h = 5 * __h + contentId.hashCode();
        }
        if(content != null)
        {
            __h = 5 * __h + content.hashCode();
        }
        if(userId != null)
        {
            __h = 5 * __h + userId.hashCode();
        }
        if(userName != null)
        {
            __h = 5 * __h + userName.hashCode();
        }
        if(nick != null)
        {
            __h = 5 * __h + nick.hashCode();
        }
        if(ip != null)
        {
            __h = 5 * __h + ip.hashCode();
        }
        if(provinceId != null)
        {
            __h = 5 * __h + provinceId.hashCode();
        }
        if(provinceName != null)
        {
            __h = 5 * __h + provinceName.hashCode();
        }
        if(isUserUBB != null)
        {
            __h = 5 * __h + isUserUBB.hashCode();
        }
        if(createTime != null)
        {
            __h = 5 * __h + createTime.hashCode();
        }
        return __h;
    }

    public java.lang.Object
    clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void
    __write(IceInternal.BasicStream __os)
    {
        __os.writeString(comId);
        __os.writeString(appId);
        __os.writeString(contentId);
        __os.writeString(content);
        __os.writeString(userId);
        __os.writeString(userName);
        __os.writeString(nick);
        __os.writeString(ip);
        __os.writeString(provinceId);
        __os.writeString(provinceName);
        __os.writeString(isUserUBB);
        __os.writeString(createTime);
    }

    public void
    __read(IceInternal.BasicStream __is)
    {
        comId = __is.readString();
        appId = __is.readString();
        contentId = __is.readString();
        content = __is.readString();
        userId = __is.readString();
        userName = __is.readString();
        nick = __is.readString();
        ip = __is.readString();
        provinceId = __is.readString();
        provinceName = __is.readString();
        isUserUBB = __is.readString();
        createTime = __is.readString();
    }

    public String getComId() {
      return comId;
    }

    public void setComId(String comId) {
      this.comId = comId;
    }

    public String getAppId() {
      return appId;
    }

    public void setAppId(String appId) {
      this.appId = appId;
    }

    public String getContentId() {
      return contentId;
    }

    public void setContentId(String contentId) {
      this.contentId = contentId;
    }

    public String getContent() {
      return content;
    }

    public void setContent(String content) {
      this.content = content;
    }

    public String getUserId() {
      return userId;
    }

    public void setUserId(String userId) {
      this.userId = userId;
    }

    public String getUserName() {
      return userName;
    }

    public void setUserName(String userName) {
      this.userName = userName;
    }

    public String getNick() {
      return nick;
    }

    public void setNick(String nick) {
      this.nick = nick;
    }

    public String getIp() {
      return ip;
    }

    public void setIp(String ip) {
      this.ip = ip;
    }

    public String getProvinceId() {
      return provinceId;
    }

    public void setProvinceId(String provinceId) {
      this.provinceId = provinceId;
    }

    public String getProvinceName() {
      return provinceName;
    }

    public void setProvinceName(String provinceName) {
      this.provinceName = provinceName;
    }

    public String getIsUserUBB() {
      return isUserUBB;
    }

    public void setIsUserUBB(String isUserUBB) {
      this.isUserUBB = isUserUBB;
    }

    public String getCreateTime() {
      return createTime;
    }

    public void setCreateTime(String createTime) {
      this.createTime = createTime;
    }
}
