// **********************************************************************
//
// Copyright (c) 2003-2010 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************

// Ice version 3.4.0

package cn.joy.ggg.api.model;

// <auto-generated>
//
// Generated from file `uac.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>


public class UACListResponse implements java.lang.Cloneable, java.io.Serializable
{
    public String code;

    public java.util.List<UAC> list;

    public UACListResponse()
    {
    }

    public UACListResponse(String code, java.util.List<UAC> list)
    {
        this.code = code;
        this.list = list;
    }

    public boolean
    equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        UACListResponse _r = null;
        try
        {
            _r = (UACListResponse)rhs;
        }
        catch(ClassCastException ex)
        {
        }

        if(_r != null)
        {
            if(code != _r.code && code != null && !code.equals(_r.code))
            {
                return false;
            }
            if(list != _r.list && list != null && !list.equals(_r.list))
            {
                return false;
            }

            return true;
        }

        return false;
    }

    public int
    hashCode()
    {
        int __h = 0;
        if(code != null)
        {
            __h = 5 * __h + code.hashCode();
        }
        if(list != null)
        {
            __h = 5 * __h + list.hashCode();
        }
        return __h;
    }

    public java.lang.Object
    clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void
    __write(IceInternal.BasicStream __os)
    {
        __os.writeString(code);
        UACListHelper.write(__os, list);
    }

    public void
    __read(IceInternal.BasicStream __is)
    {
        code = __is.readString();
        list = UACListHelper.read(__is);
    }

    public String getCode() {
      return code;
    }

    public void setCode(String code) {
      this.code = code;
    }

    public java.util.List<UAC> getList() {
      return list;
    }

    public void setList(java.util.List<UAC> list) {
      this.list = list;
    }
}
