// **********************************************************************
//
// Copyright (c) 2003-2010 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************

// Ice version 3.4.0

package cn.joy.ggg.api.model;

// <auto-generated>
//
// Generated from file `community.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>


public class Video implements java.lang.Cloneable, java.io.Serializable
{
    public String cover;

    public String path;

    public String format;

    public String quality;

    public String width;

    public String height;

    public int length;

    public int size;

    public String protocol;

    public String remark;

    public Video()
    {
    }

    public Video(String cover, String path, String format, String quality, String width, String height, int length, int size, String protocol, String remark)
    {
        this.cover = cover;
        this.path = path;
        this.format = format;
        this.quality = quality;
        this.width = width;
        this.height = height;
        this.length = length;
        this.size = size;
        this.protocol = protocol;
        this.remark = remark;
    }

    public boolean
    equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        Video _r = null;
        try
        {
            _r = (Video)rhs;
        }
        catch(ClassCastException ex)
        {
        }

        if(_r != null)
        {
            if(cover != _r.cover && cover != null && !cover.equals(_r.cover))
            {
                return false;
            }
            if(path != _r.path && path != null && !path.equals(_r.path))
            {
                return false;
            }
            if(format != _r.format && format != null && !format.equals(_r.format))
            {
                return false;
            }
            if(quality != _r.quality && quality != null && !quality.equals(_r.quality))
            {
                return false;
            }
            if(width != _r.width && width != null && !width.equals(_r.width))
            {
                return false;
            }
            if(height != _r.height && height != null && !height.equals(_r.height))
            {
                return false;
            }
            if(length != _r.length)
            {
                return false;
            }
            if(size != _r.size)
            {
                return false;
            }
            if(protocol != _r.protocol && protocol != null && !protocol.equals(_r.protocol))
            {
                return false;
            }
            if(remark != _r.remark && remark != null && !remark.equals(_r.remark))
            {
                return false;
            }

            return true;
        }

        return false;
    }

    public int
    hashCode()
    {
        int __h = 0;
        if(cover != null)
        {
            __h = 5 * __h + cover.hashCode();
        }
        if(path != null)
        {
            __h = 5 * __h + path.hashCode();
        }
        if(format != null)
        {
            __h = 5 * __h + format.hashCode();
        }
        if(quality != null)
        {
            __h = 5 * __h + quality.hashCode();
        }
        if(width != null)
        {
            __h = 5 * __h + width.hashCode();
        }
        if(height != null)
        {
            __h = 5 * __h + height.hashCode();
        }
        __h = 5 * __h + length;
        __h = 5 * __h + size;
        if(protocol != null)
        {
            __h = 5 * __h + protocol.hashCode();
        }
        if(remark != null)
        {
            __h = 5 * __h + remark.hashCode();
        }
        return __h;
    }

    public java.lang.Object
    clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void
    __write(IceInternal.BasicStream __os)
    {
        __os.writeString(cover);
        __os.writeString(path);
        __os.writeString(format);
        __os.writeString(quality);
        __os.writeString(width);
        __os.writeString(height);
        __os.writeInt(length);
        __os.writeInt(size);
        __os.writeString(protocol);
        __os.writeString(remark);
    }

    public void
    __read(IceInternal.BasicStream __is)
    {
        cover = __is.readString();
        path = __is.readString();
        format = __is.readString();
        quality = __is.readString();
        width = __is.readString();
        height = __is.readString();
        length = __is.readInt();
        size = __is.readInt();
        protocol = __is.readString();
        remark = __is.readString();
    }

    public String getCover() {
      return cover;
    }

    public void setCover(String cover) {
      this.cover = cover;
    }

    public String getPath() {
      return path;
    }

    public void setPath(String path) {
      this.path = path;
    }

    public String getFormat() {
      return format;
    }

    public void setFormat(String format) {
      this.format = format;
    }

    public String getQuality() {
      return quality;
    }

    public void setQuality(String quality) {
      this.quality = quality;
    }

    public String getWidth() {
      return width;
    }

    public void setWidth(String width) {
      this.width = width;
    }

    public String getHeight() {
      return height;
    }

    public void setHeight(String height) {
      this.height = height;
    }

    public int getLength() {
      return length;
    }

    public void setLength(int length) {
      this.length = length;
    }

    public int getSize() {
      return size;
    }

    public void setSize(int size) {
      this.size = size;
    }

    public String getProtocol() {
      return protocol;
    }

    public void setProtocol(String protocol) {
      this.protocol = protocol;
    }

    public String getRemark() {
      return remark;
    }

    public void setRemark(String remark) {
      this.remark = remark;
    }
}
