// **********************************************************************
//
// Copyright (c) 2003-2010 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************

// Ice version 3.4.0

package cn.joy.ggg.api.service;

// <auto-generated>
//
// Generated from file `message.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>


public interface MessageServicePrx extends Ice.ObjectPrx
{
    public cn.joy.ggg.api.model.MessageResponse sendMessage(String source, String dest, String msg);

    public cn.joy.ggg.api.model.MessageResponse sendMessage(String source, String dest, String msg, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_sendMessage(String source, String dest, String msg);

    public Ice.AsyncResult begin_sendMessage(String source, String dest, String msg, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_sendMessage(String source, String dest, String msg, Ice.Callback __cb);

    public Ice.AsyncResult begin_sendMessage(String source, String dest, String msg, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_sendMessage(String source, String dest, String msg, Callback_MessageService_sendMessage __cb);

    public Ice.AsyncResult begin_sendMessage(String source, String dest, String msg, java.util.Map<String, String> __ctx, Callback_MessageService_sendMessage __cb);

    public cn.joy.ggg.api.model.MessageResponse end_sendMessage(Ice.AsyncResult __result);

    public cn.joy.ggg.api.model.MessageResponse getMessageList(String source, int start, int count);

    public cn.joy.ggg.api.model.MessageResponse getMessageList(String source, int start, int count, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getMessageList(String source, int start, int count);

    public Ice.AsyncResult begin_getMessageList(String source, int start, int count, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getMessageList(String source, int start, int count, Ice.Callback __cb);

    public Ice.AsyncResult begin_getMessageList(String source, int start, int count, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_getMessageList(String source, int start, int count, Callback_MessageService_getMessageList __cb);

    public Ice.AsyncResult begin_getMessageList(String source, int start, int count, java.util.Map<String, String> __ctx, Callback_MessageService_getMessageList __cb);

    public cn.joy.ggg.api.model.MessageResponse end_getMessageList(Ice.AsyncResult __result);

    public cn.joy.ggg.api.model.MessageResponse removeMessage(String source, int msgId);

    public cn.joy.ggg.api.model.MessageResponse removeMessage(String source, int msgId, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_removeMessage(String source, int msgId);

    public Ice.AsyncResult begin_removeMessage(String source, int msgId, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_removeMessage(String source, int msgId, Ice.Callback __cb);

    public Ice.AsyncResult begin_removeMessage(String source, int msgId, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_removeMessage(String source, int msgId, Callback_MessageService_removeMessage __cb);

    public Ice.AsyncResult begin_removeMessage(String source, int msgId, java.util.Map<String, String> __ctx, Callback_MessageService_removeMessage __cb);

    public cn.joy.ggg.api.model.MessageResponse end_removeMessage(Ice.AsyncResult __result);
}
